import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import { Theme, Flex, Box } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import '@radix-ui/themes/layout.css';
import "./globals.css";
import Nav from "./components/navigation/nav";
import Footer from "./components/footer/footer";
import Image from "next/image";

const space_mono = Space_Mono({weight: "400", subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Alessandro Marotta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={space_mono.className}>
        <Theme appearance="dark">
            <div style={{zIndex: -1, position: "fixed", width: "100vw", height: "100vh"}}>
              <Image src="/bg.jpg" alt="Not found" layout="fill" objectFit="cover"/>
            </div>
            <Flex direction="column">
              <Box style={{ flex: 1 }}>
                <Nav />
                {children}
              </Box>
            <Footer />
          </Flex>
        </Theme>
      </body>
    </html>
  );
}
