import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import { Theme, Flex, Box } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import '@radix-ui/themes/layout.css';
import "./globals.css";
import Nav from "./components/navigation/nav";
import Footer from "./components/footer/footer";

const space_mono = Space_Mono({weight: "400", subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Alessandro Marotta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={space_mono.className}>
        <Theme appearance="dark">
            <Flex direction="column" style={{ minHeight: '100vh' }}>
              <Box style={{ flex: 1 }}>
                <Nav />
                <main>{children}</main>
              </Box>
            <Footer />
          </Flex>
        </Theme>
      </body>
    </html>
  );
}
